version: '3'
services:
  web:
    image: nginx:stable-bookworm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./landing:/usr/share/nginx/html
      - ./assets:/usr/share/nginx/html/assets
      - ./editor/dist:/usr/share/nginx/html/editor
    ports:
      - "80:80"
